<?php declare(strict_types=1);

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2AdditionalSniffs.Templates.ConsoleLog

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hyva\Checkout\Magewire\Checkout\AddressView\AbstractMagewireAddressForm $magewire */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */

/** @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);

// Note: the JS functions referenced in this alpine component can be found in validation-status-js.phtml.
// The reason thay are seperated is because this component gets hidden by magewire based on conditions (see
// ShippingAdddressModifiers). By placing the JS in a seperate file, that's always loaded we avoid any errors.

?>
<div id="vat-request-status"
     x-data="initVatButton()"
     x-init="
        $watch('showFrontendMessage', value => closeMessage());
        vatNumber = '<?= $escaper->escapeJs($magewire->address['vat_id'] ?? '')?>';
        countryId = '<?= $escaper->escapeJs($magewire->address['country_id'] ?? '')?>';
        autoSaveTime = '<?= $escaper->escapeJs($magewire->getAutoSaveTimeout())?>';
     "
     @country-id-changed.window="countryId = $event.detail; resetValidation()"
     @vat-id-changed.window="validate($event.detail)"
>
    <div class="rounded-md p-4 my-2"
         :class="{'bg-green-50': vatIsValid, 'bg-red-50': ! vatIsValid}"
         x-show="showFrontendMessage"
         x-transition
    >
        <div class="flex">
            <div class="flex-shrink-0">
                <div x-show="vatIsValid" class="text-green-400">
                    <?= /* @noEscape */ $heroIcons->checkCircleHtml('h-5 w-5 stroke-green-400') ?>
                </div>
                <div x-show="!vatIsValid" class="text-red-400">
                    <?= /* @noEscape */ $heroIcons->exclamationCircleHtml('h-5 w-5 stroke-red-400') ?>
                </div>
            </div>
            <div class="ml-3">
                <p x-text="requestMessage"
                   :class="{'text-green-800': vatIsValid, 'text-red-800': ! vatIsValid}"
                   class="text-sm font-medium"></p>
            </div>
            <div class="ml-auto cursor-pointer" @click="closeMessage(0)">
                <?= /* @noEscape */ $heroIcons->xHtml('h-5 w-5') ?>
            </div>
        </div>
    </div>
</div>
