<?php declare(strict_types=1);

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2AdditionalSniffs.Templates.ConsoleLog

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Hyva\Checkout\Magewire\Checkout\AddressView\AbstractMagewireAddressForm $magewire */
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */

/** @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(\Hyva\Theme\ViewModel\HeroiconsOutline::class);

$initialValue = $magewire->address['vat_id'] ?? '';
$initialCountryId = $magewire->address['country_id'] ?? '';
?>
<div id="vat-request-button"
     x-data="initVatButton()"
     x-init="$watch('showFrontendMessage', value => closeMessage());"
     @country-id-changed.window="countryId = $event.detail; resetValidation()"
     @vat-id-changed.window="validate($event.detail)"
>
    <div class="rounded-md p-4 my-2"
         :class="{'bg-green-50': vatIsValid, 'bg-red-50': ! vatIsValid}"
         x-show="showFrontendMessage"
         x-transition
    >
        <div class="flex">
            <div class="flex-shrink-0">
                <div x-show="vatIsValid" class="text-green-400">
                    <?= /* @noEscape */ $heroIcons->checkCircleHtml('h-5 w-5 stroke-green-400') ?>
                </div>
                <div x-show="!vatIsValid" class="text-red-400">
                    <?= /* @noEscape */ $heroIcons->exclamationCircleHtml('h-5 w-5 stroke-red-400') ?>
                </div>
            </div>
            <div class="ml-3">
                <p x-text="requestMessage"
                   :class="{'text-green-800': vatIsValid, 'text-red-800': ! vatIsValid}"
                   class="text-sm font-medium"></p>
            </div>
            <div class="ml-auto cursor-pointer" @click="closeMessage(0)">
                <?= /* @noEscape */ $heroIcons->xHtml('h-5 w-5') ?>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('initVatButton', () => {
            return {
                vatNumber: '<?= $escaper->escapeJs($initialValue) ?>',
                countryId: '<?= $escaper->escapeJs($initialCountryId) ?>',
                requestMessage: '',
                vatIsValid: false,
                showFrontendMessage: false,

                get isVatNumberFilled() {
                    return this.vatNumber.length > 0;
                },

                /**
                 * Get the country code from the VAT number
                 * @returns {string}
                 */
                get countryCodeFromVatNumber() {
                    if (this.vatNumber.match(new RegExp('^[A-Z][A-Z]'))) {
                        return this.vatNumber.substr(0, 2).toUpperCase();
                    }
                    return '';
                },

                /**
                 * Reset the validation
                 * @returns {void}
                 */
                resetValidation() {
                    this.showFrontendMessage = false;
                    this.requestMessage = '';
                    this.vatIsValid = false;
                    this.refreshPrices();
                },

                /**
                 * Close frontend message with timout.
                 * @param timeout
                 * @returns {void}
                 */
                closeMessage(timeout = 10000) {
                    setTimeout(() => {
                        this.showFrontendMessage = false;
                        this.requestMessage = '';
                    }, timeout);
                },

                showInvalidCountryMessage() {
                    this.vatIsValid = false;
                    this.requestMessage = '<?= $escaper->escapeJs(
                        __('The country code from the VAT number does not match the selected country.')->render()
                    ) ?>';
                    this.showFrontendMessage = true;
                    this.refreshPrices();
                },

                refreshPrices() {
                    //Trigger update order total summary
                    setTimeout(() => {
                        Magewire.emitTo('price-summary.total-segments', 'refresh');
                    }, <?= $escaper->escapeJs($magewire->getAutoSaveTimeout()) ?>);
                },

                validate(vatNumber) {
                    this.vatNumber = vatNumber;
                    this.showFrontendMessage = false;

                    if (!this.isVatNumberFilled) {
                        return;
                    }

                    if (this.countryCodeFromVatNumber !== this.countryId) {
                        this.showInvalidCountryMessage();
                        return;
                    }

                    console.debug(`Start VAT validation ${this.vatNumber} for country ${this.countryId}`);

                    const requestUrl = `${BASE_URL}euvat/vatnumber/validation`;
                    const params = new URLSearchParams({
                        form_key: hyva.getFormKey(),
                        vat_number: this.vatNumber,
                        handle: 'hyva_front'
                    });

                    fetch(requestUrl + '?' + params, {
                        headers: {'X-Requested-With': 'XMLHttpRequest'},
                        method: 'GET',
                        mode: 'cors',
                        credentials: 'include'
                    })
                        .then(response => {
                            if (!response.ok) console.warn('GET request failed');
                            return response.json();
                        })
                        .then(data => {
                            console.debug(data);
                            if (data.request_message !== undefined) {
                                this.requestMessage = data.request_message;
                            }
                            if (data.vat_is_valid !== undefined) {
                                this.vatIsValid = data.vat_is_valid;
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                        })
                        .finally(() => {
                            this.showFrontendMessage = true;
                            this.refreshPrices();
                        });
                }
            };
        });
    });
</script>
